/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:78e4327a-22d1-4ac6-8507-ad0107403540",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_IS6IKFJmS",
    "aws_user_pools_web_client_id": "4t4vot1jspjif8mouqlv44mj87",
    "oauth": {}
};


export default awsmobile;
