/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:78e4327a-22d1-4ac6-8507-ad0107403540",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_IS6IKFJmS",
    "aws_user_pools_web_client_id": "4t4vot1jspjif8mouqlv44mj87",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gyefbbjcubdtlfsw5qecjg7aha.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mh66a3ok3repracytqlqpscgz4",
    "aws_user_files_s3_bucket": "bucket033133-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
